version: "3.9"
services:
  node_web_controller:
    build:
      context: web_controller/
      dockerfile: ../base/Dockerfile
      args:
        NODE_NAME: web_controller
    ports:
      - 8080:8080

  node_robot_platform:
    build:
      context: robot_platform/
      dockerfile: ../base/Dockerfile
      args:
        NODE_NAME: robot_platform

  node_distance_sensor:
    build:
      context: distance_sensor/
      dockerfile: ../base/Dockerfile
      args:
        NODE_NAME: distance_sensor

  node_environment_scanner:
    build:
      context: environment_scanner/
      dockerfile: ../base/Dockerfile
      args:
        NODE_NAME: environment_scanner
